### ISSUE TITLE
Question about the Bank OTP app

### ISSUE THREAD

**Issue by overture8** [wojtekmach/acme_bank#13]
I have a question about the `Bank` OTP app. Is my understanding correct that it is a higher level app that controls how the other lower level (`Auth` etc) interact? Also, would it be possible for there to be multiple higher level apps in order to split up the business logic or is there generally just one?

Hope this makes sense. Thanks so much :)

**Comment by wojtekmach** [comment]
My current rule of thumb is to extract an app if:

a) it doesn't seem app specific and it's reasonable to have it as Hex package (even if it never gets OSSed)
b) I want to deploy it separately and/or it has separate storage

So for AcmeBank good candidates for separate apps would be some 3rd party service wrappers (that could be Hex packages eventually) or maybe `FraudDetector` that does some ML stuff off DB (probably bypassing Ecto). That being said, I have `apps/auth` which does not fit either of these criteria and looking back, I think this extraction was a bit premature. Especially that in theory it has separate Repo from Bank and the schemas are not associated in any way, but in practice in both dev and "prod" it ends up running on the same PG db.

Another angle is to look what logic I consider unique to my app, what's really the value added (that I'd keep in core OTP app) and what's still needed but not quite my core competency (`apps/messenger` is a good example of that). To answer your question, I probably would not split up business logic into separate apps unless you can draw a really clear line and in the meantime use good code organisation within one OTP app to keep it ~well organised~ maintainable.

**Comment by overture8** [comment]
Thanks @wojtekmach - that makes sense. Thanks for the lightning fast reply :)
