### ISSUE TITLE
Auth: link to customer account

### ISSUE THREAD

**Issue by benrom** [wojtekmach/acme_bank#4]
Looking at the code I see that the user account has a "foreign key" to the authentication:

``` elixir
schema "bank_customers" do
  field :auth_account_id, :integer
```

Shouldn't this relation be inversed: auth linking to the underlying customer ?

``` elixir
schema "auth_accounts" do
  field :customer_id, :integer
```

This would bring more modularity: being able to swap/add authentication methods in the future without changing the customer model.
It's still easy to use: the session bit authenticates the user and we get the customer_id without going through an extra query (if we're only interested in the id).

I thought that was what slide 112 was all about, it enlightened me!
Though the implementation I found brought me down a bit..

Tell me what you think!

**Comment by wojtekmach** [comment]
Hey @benrom, thanks for bringing this up! I think you're right, at this moment (and taking different auth providers into account) moving foreign key to the `auth_accounts` makes a lot of sense.

What I was thinking at the time was that there might be an additional user-like record in the backoffice app, in which case there would need to be `auth_accounts.{customer_id, backoffice_user_id}` which I didn't like (N-colums for N apps). However, I never added it and I'm not sure if that was ever a good idea :-) I specifically wanted to keep is simple. Yet another approach, that I got from @chrismccord, is to have `auth_accounts.{app_id, user_id}` and that's probably the way to go for multiple apps.

**Comment by benrom** [comment]
Ok, thanks for your feedback there!
Yeah, using the same table as customers for authenticating backoffice users is generally not a recommended approach for security reasons anyway.
Thank you for having this project there, it's me a lot for elixir app design!

**Comment by benrom** [comment]
Sadly having played a bit with Ecto, it seems like it only allows the owning side of the relationship to be the `belongs_to` (child) and not the `has_*` (parent) : whenever you want to preload the associated value it automatically looks for the foreign key on the `belongs_to` table.
So it looks like your implementation there is the only way to do it with Ecto.
