### ISSUE TITLE
Question Related To MasterProxy

### ISSUE THREAD

**Issue by blisscs** [wojtekmach/acme_bank#7]
Hello,

I have question related to MasterProxy.
In the code below

```
 cond do
      conn.request_path =~ ~r{/backoffice} ->
        Backoffice.Endpoint.call(conn, [])
      true ->
        BankWeb.Endpoint.call(conn, [])
    end
```

It's uses /backoffice regular expression to dispatch to two endpoints.
I think we still missing something in here. In both the endpoints, there are assets is fetched through static_plug in both the endpoints. Do you know how to edit the code to cover those cases also. 

Thanks
Dev.

**Comment by blisscs** [comment]
Sorry for the issue.
I see in the static_plug that the plug static is at "/backoffice" so it is already namespaced

**Comment by wojtekmach** [comment]
no worries, thanks for posting the answer! :-)
